version: '2'
services:
    campuz360-app:
        image: campuz360
        external_links:
            - campuz360-mysql:mysql
            - campuz360-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/campuz360?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    campuz360-mysql:
        extends:
            file: mysql.yml
            service: campuz360-mysql
    campuz360-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: campuz360-elasticsearch
