version: '2'
services:
    campuz360-mysql:
        container_name: campuz360-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/Campuz360/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=campuz360
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
